### ISSUE TITLE
Creates a 1px gap at the top when fullscreen

### ISSUE THREAD

**Issue by mattpepin** [fthx/hide-panel#4] opened 2021-04-05 10:37 UTC
With this extension enabled, full-screen apps leave a 1px gap at the top of the screen:

![image](https://user-images.githubusercontent.com/582959/113565603-36841600-95d9-11eb-8c12-52c82d9b90d1.png)

It's kind of small in the screenshot, but if the app has a dark background, it's really noticeable.

**Comment by fthx** [comment] 2021-04-05 14:12
It's by design.
It allows to not modify in any way GS more than this hiding.
0px causes the hot corner to be disabled.

I realized that with some use, it's quite easy to click in this 1px line to blindly access top menus, so I find this quite handy.
The proposal could be to make this line really black, I'm open for a PR here!

I close this but feel free to send a PR, if it keeps the extension stupidly simple as it is.

**Closed as completed by fthx** 2021-04-05 14:12 UTC
